=== AlessandroVOliveira/Fileblocks/samples/notes.dtd
<!-- Sample DTD for notes.xml -->
<!ENTITY % priority "(low|normal|high)">

<!-- A collection of notes. -->
<!ELEMENT notes (owner, note+)>
<!ATTLIST notes version CDATA #FIXED "1.0">

<!-- Who the notes belong to. -->
<!ELEMENT owner (#PCDATA)>

<!-- One note: a title, a body and optional tags. -->
<!ELEMENT note (title, body, tag*)>
<!ATTLIST note
  id       ID            #REQUIRED
  priority %priority;    "normal"
  archived (yes|no)      #IMPLIED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT body (#PCDATA | em | link)*>
<!ELEMENT em (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link href CDATA #REQUIRED>
<!ELEMENT tag EMPTY>
<!ATTLIST tag name NMTOKEN #REQUIRED>

=== AlessandroVOliveira/Fileblocks/samples/notes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE notes SYSTEM "notes.dtd">
<notes version="2.0">
  <owner>Jane Doe</owner>
  <note id="n1" priority="urgent">
    <title>Groceries</title>
    <body>Buy <em>milk</em> and see <link>the list</link></body>
    <tag name="home"/>
    <tag name="two words"/>
  </note>
  <note archived="maybe">
    <body>Missing title</body>
  </note>
  <memo>Not declared</memo>
</notes>
